@startuml

title Use Case Diagram Sistem Pelaporan Kejahatan Online (SIPO)

actor "Masyarakat" as user
actor "Admin Kepolisian" as admin
actor "Petugas Polisi" as officer

usecase "Melapor" as UC_Melapor
usecase "Melihat Laporan" as UC_MelihatLaporan
usecase "Membuat Laporan" as UC_MembuatLaporan
usecase "Memberikan Laporan" as UC_MemberikanLaporan
usecase "Status Laporan" as UC_StatusLaporan
usecase "Melakukan Tugas" as UC_MelakukanTugas

user -- UC_Melapor
user -- UC_MelihatLaporan

admin -- UC_MembuatLaporan
admin -- UC_MelihatLaporan
admin -- UC_StatusLaporan

officer -- UC_MemberikanLaporan
officer -- UC_StatusLaporan
officer -- UC_MelakukanTugas

@enduml