@startuml test.puml
' Mengatur font global menjadi Times New Roman
skinparam DefaultFontName "Times New Roman"
skinparam DefaultFontSize 12

' Pengaturan visual agar mirip dengan gambar
skinparam Shadowing false
skinparam RoundCorner 0
skinparam BackgroundColor white

rectangle "Input File\n(Plaintext)" as input #f2f2f2
rectangle "Modul Kriptografi\n(AES-256 & PBKDF2)" as module #f2f2f2
rectangle "Output File\n(Ciphertext / Decrypted File)" as output #f2f2f2

input -right-> module : Password User
module -right-> output
@enduml