@startuml
scale 2
title Grafik Proyeksi Pendapatan 6 Bulan

start
:Proyeksi Pendapatan (IDR);
:Kenaikan Pendapatan Stabil Setiap Bulan;

partition "Bulan 1" {
  :12.000.000 IDR;
}
partition "Bulan 2" {
  :15.000.000 IDR;
}
partition "Bulan 3" {
  :18.000.000 IDR;
}
partition "Bulan 4" {
  :20.000.000 IDR;
}
partition "Bulan 5" {
  :22.000.000 IDR;
}
partition "Bulan 6" {
  :25.000.000 IDR;
}

stop
@enduml
